BULK INSERT dbo.MEDIA_DOCUMENTS_STAGE
FROM '/var/opt/mssql/data/MAGIQ_Docs-data.csv'
WITH
(
    FORMAT = 'CSV',
    FIRSTROW = 2
);


CREATE TABLE dbo.MEDIA_DOCUMENTS_STAGE
(
    CPSETSAVEDBYID nvarchar(max),
    CPSETSAVEDBYNAME nvarchar(max),
    CPSETSAVEDDATE nvarchar(max),
    CUSTOMER_ID nvarchar(max),
    HOUSE_LOCATION nvarchar(max),
    LETTER_NAME nvarchar(max),
    OBJECTID nvarchar(max),
    OBJECTTYPE nvarchar(max),
    OWNER_ID nvarchar(max),
    ROWNBR nvarchar(max),
    STREET_ID nvarchar(max),
    VALUATION_ID nvarchar(max),
    APPLICANT_NAME nvarchar(max),
    CONSENT_ID nvarchar(max),
    PROPERTY_ID nvarchar(max),
    PROPOSAL nvarchar(max),
    RA_LOCATION nvarchar(max),
    CE_ID nvarchar(max),
    CEMETERY_CODE nvarchar(max),
    DATE_OF_DEATH nvarchar(max),
    DATE_OF_INTERMENT nvarchar(max),
    FIRST_NAMES nvarchar(max),
    SURNAME nvarchar(max),
    COMPLIANCE_SCHEDULE_ID nvarchar(max),
    CREDITOR_ID nvarchar(max),
    FULL_NAME nvarchar(max),
    APPLICATION_ACCOUNT_ID nvarchar(max),
    APPLICATION_ID nvarchar(max),
    DEBT_MANAGEMENT_ID nvarchar(max),
    DM_NAME_KEY nvarchar(max),
    DEBTOR_ID nvarchar(max),
    ACCOUNT_ID nvarchar(max),
    DEBTOR_NAME nvarchar(max),
    LEDGER nvarchar(max),
    MASTERFILE_UNIQUE_ID nvarchar(max),
    INFRINGEMENT_ID nvarchar(max),
    OWNER_NAME nvarchar(max),
    GL_ID nvarchar(max),
    GL_NAME nvarchar(max),
    INVOICE_DATE nvarchar(max),
    INVOICE_ID nvarchar(max),
    INVOICE_NUMBER nvarchar(max),
    BUSINESS_DETAIL nvarchar(max),
    LICENCE_DETAIL nvarchar(max),
    LICENCE_ID nvarchar(max),
    LICENSEE_NAME nvarchar(max),
    LOCATION nvarchar(max),
    LIM_ID nvarchar(max),
    PROJECT_ID nvarchar(max),
    PROJECT_NAME nvarchar(max),
    RG_LEGAL_DESCRIPTION nvarchar(max),
    RG_LOCATION nvarchar(max),
    LEGAL_DESCRIPTION nvarchar(max),
    RATEPAYER_NAME_1 nvarchar(max),
    RATEPAYER_NAME_2 nvarchar(max),
    RA_LEGAL_DESCRIPTION nvarchar(max),
    REBATE_ID nvarchar(max),
    CALLER_NAME nvarchar(max),
    RECORD_ID nvarchar(max),
    CUSTOMER_NAME nvarchar(max),
    WATER_ID nvarchar(max),
    SourceTable nvarchar(max),
    DOCUMENT_ID nvarchar(max),
    DOCUMENT_NAME nvarchar(max),
    DOCUMENT_DESCRIPTION nvarchar(max),
    DOCUMENT_REGISTERDATE nvarchar(max),
    DOCUMENT_AUTHOR nvarchar(max),
    DOCUMENT_OWNER nvarchar(max),
    DOCUMENT_TYPE nvarchar(max),
    DOCUMENT_SIZE nvarchar(max),
    DOCUMENT_SOURCE nvarchar(max),
    FOLDER_ID nvarchar(max),
    FOLDER_PATH nvarchar(max),
    WH_PATH nvarchar(max)
);

INSERT INTO dbo.MEDIA_DOCS
(
    CPSETSAVEDBYID,
    CPSETSAVEDBYNAME,
    CPSETSAVEDDATE,
    CUSTOMER_ID,
    HOUSE_LOCATION,
    LETTER_NAME,
    OBJECTID,
    OBJECTTYPE,
    OWNER_ID,
    ROWNBR,
    STREET_ID,
    VALUATION_ID,
    APPLICANT_NAME,
    CONSENT_ID,
    PROPERTY_ID,
    PROPOSAL,
    RA_LOCATION,
    CE_ID,
    CEMETERY_CODE,
    DATE_OF_DEATH,
    DATE_OF_INTERMENT,
    FIRST_NAMES,
    SURNAME,
    COMPLIANCE_SCHEDULE_ID,
    CREDITOR_ID,
    FULL_NAME,
    APPLICATION_ACCOUNT_ID,
    APPLICATION_ID,
    DEBT_MANAGEMENT_ID,
    DM_NAME_KEY,
    DEBTOR_ID,
    ACCOUNT_ID,
    DEBTOR_NAME,
    LEDGER,
    MASTERFILE_UNIQUE_ID,
    INFRINGEMENT_ID,
    OWNER_NAME,
    GL_ID,
    GL_NAME,
    INVOICE_DATE,
    INVOICE_ID,
    INVOICE_NUMBER,
    BUSINESS_DETAIL,
    LICENCE_DETAIL,
    LICENCE_ID,
    LICENSEE_NAME,
    LOCATION,
    LIM_ID,
    PROJECT_ID,
    PROJECT_NAME,
    RG_LEGAL_DESCRIPTION,
    RG_LOCATION,
    LEGAL_DESCRIPTION,
    RATEPAYER_NAME_1,
    RATEPAYER_NAME_2,
    RA_LEGAL_DESCRIPTION,
    REBATE_ID,
    CALLER_NAME,
    RECORD_ID,
    CUSTOMER_NAME,
    WATER_ID,
    SourceTable,
    DOCUMENT_ID,
    DOCUMENT_NAME,
    DOCUMENT_DESCRIPTION,
    DOCUMENT_REGISTERDATE,
    DOCUMENT_AUTHOR,
    DOCUMENT_OWNER,
    DOCUMENT_TYPE,
    DOCUMENT_SIZE,
    DOCUMENT_SOURCE,
    FOLDER_ID,
    FOLDER_PATH,
    WH_PATH
)
SELECT
    CPSETSAVEDBYID,
    CPSETSAVEDBYNAME,
    CPSETSAVEDDATE,
    CUSTOMER_ID,
    HOUSE_LOCATION,
    LETTER_NAME,
    OBJECTID,
    OBJECTTYPE,
    OWNER_ID,
    ROWNBR,
    STREET_ID,
    VALUATION_ID,
    APPLICANT_NAME,
    CONSENT_ID,
    PROPERTY_ID,
    PROPOSAL,
    RA_LOCATION,
    CE_ID,
    CEMETERY_CODE,
    DATE_OF_DEATH,
    DATE_OF_INTERMENT,
    FIRST_NAMES,
    SURNAME,
    COMPLIANCE_SCHEDULE_ID,
    CREDITOR_ID,
    FULL_NAME,
    APPLICATION_ACCOUNT_ID,
    APPLICATION_ID,
    DEBT_MANAGEMENT_ID,
    DM_NAME_KEY,
    DEBTOR_ID,
    ACCOUNT_ID,
    DEBTOR_NAME,
    LEDGER,
    MASTERFILE_UNIQUE_ID,
    INFRINGEMENT_ID,
    OWNER_NAME,
    GL_ID,
    GL_NAME,
    INVOICE_DATE,
    INVOICE_ID,
    INVOICE_NUMBER,
    BUSINESS_DETAIL,
    LICENCE_DETAIL,
    LICENCE_ID,
    LICENSEE_NAME,
    LOCATION,
    LIM_ID,
    PROJECT_ID,
    PROJECT_NAME,
    RG_LEGAL_DESCRIPTION,
    RG_LOCATION,
    LEGAL_DESCRIPTION,
    RATEPAYER_NAME_1,
    RATEPAYER_NAME_2,
    RA_LEGAL_DESCRIPTION,
    REBATE_ID,
    CALLER_NAME,
    RECORD_ID,
    CUSTOMER_NAME,
    WATER_ID,
    SourceTable,
    TRY_CONVERT(int, NULLIF(DOCUMENT_ID, '')),
    DOCUMENT_NAME,
    DOCUMENT_DESCRIPTION,
    TRY_CONVERT(datetime, NULLIF(DOCUMENT_REGISTERDATE, '')),
    DOCUMENT_AUTHOR,
    DOCUMENT_OWNER,
    DOCUMENT_TYPE,
    TRY_CONVERT(int, NULLIF(DOCUMENT_SIZE, '')),
    DOCUMENT_SOURCE,
    TRY_CONVERT(int, NULLIF(FOLDER_ID, '')),
    FOLDER_PATH,
    WH_PATH
FROM dbo.MEDIA_DOCUMENTS_STAGE;